
steps:
# [build or rebuild image]
- name: 'gcr.io/cloud-builders/docker' # standard container name
  # exec command
  entrypoint: docker
  args: ['build', '-t', 'asia.gcr.io/django-api-289204/django-api:latest', '.']

# [push image]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: docker
  args: ['push', 'asia.gcr.io/django-api-289204/django-api:latest']

  # [deploy image]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args: ['run', 'deploy', 'django-api', '--region', 'asia-northeast1', '--image', 'asia.gcr.io/django-api-289204/django-api:latest', '--port', '8000', '--platform', 'managed']

#   # [test]
# - name: 'python'
#   entrypoint: python
#   args: ['code/test.py']

# GCR image name
images:
  - asia.gcr.io/django-api-289204/django-api:latest
